### PR TITLE
No leaks now in the first ListView test.

### PR DESCRIPTION
**Pull request by t-johnson**
Doesn't seem to leak for me when run in Release mode on IOS Simulator.

### CODE REVIEW

**Comment by t-johnson** [comment]
@AlanYost looks like whitespace got changed in my commit - compare with ignoring whitespace to see the changes.

**Comment by AlanYost** [comment]
Thanks @t-johnson - I'll give it a blast in a while.  Heading out soon for a few hours but will be back to test.  I really appreciate your input.

**Comment by t-johnson** [comment]
@AlanYost  you're too quick!  i just realized i missed some files when i committed.

**Comment by AlanYost** [comment]
@t-johnson - Mmmm not sure what is different between our environments but my physical iPad running iOS 14.4 is still leaking on the ListView.  You have to set the Items count to 50 and then goto the listview and tap on a few different rows whilst also scrolling in between taps.  It always leaks for me if I do that....  Are you pointing to the same XF nuget package?

**Comment by VladYambay** [comment]
I have retested the latest changes where the ListView binds directly to the ObservableCollection in the view model with Xamarin.Forms 5.0.0.6998 on a physical iPad device (iOS 14.3). I can confirm that it's still leaking memory in the ListView test with Items count set to **50** and tapping **three** times or more on any row to reload the collection of items. Please note that it does **not** leak memory if I tap one or two times, the issue appears only when I tap **3** or more times and use more than **20** items in the collection (might depend on how many items can fit on the screen of a testing device). 

@t-johnson , @AlanYost  - FYI and thank you for looking into this issue.

**Comment by t-johnson** [comment]
@VladYambay can confirm - clicking **three** times with 50 items seems to trigger the leak.  
and @AlanYost, I am only testing against the last stable release of Xamarin Forms 5.

**Comment by t-johnson** [comment]
This sample might be suffering from memory leaks that are addressed in https://github.com/xamarin/Xamarin.Forms/pull/12535
In that case, there were several places where modifications to the collection the list is bound to would leak. this was fixing grouped listviews, but i believe the fix also addresses similarissues in non-grouped listviews.
i've no idea why it takes so long for a PR to get approved in the XamarinForms project... its kind of frustrating as both these PRs i did are now 3+ months old...

**Pull request merged**
